version: '3.8'

services:
  nest-app:
    env_file:
      - ./src/config/.env
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      mysql-container:
        condition: service_healthy
      redis-container:
        condition: service_started
    ports:
      - '3008:3008'
    networks:
      - common-network
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mysql-container:3306/${MYSQL_DATABASE}
      - REDIS_HOST=redis-container
      - REDIS_PORT=6379
    restart: always

  mysql-container:
    image: mysql:8.0
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - common-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  redis-container:
    image: redis:6.2
    volumes:
      - ./data/redis:/data
    networks:
      - common-network
    restart: always
    command: redis-server --appendonly yes

networks:
  common-network:
    driver: bridge
