application:
  port: 3008
  prefix: ""

  # 日志配置
  logger:
    info:
      level: 'debug'
      filename: 'info-%DATE%.log'
      dirname: 'logs/%DATE%'
      datePattern: 'YYYY-MM-DD'
      # 文件大小限制，单位M
      maxSize: '10M'
    error:
      level: 'error'
      filename: 'error-%DATE%.log'
      dirname: 'logs/%DATE%'
      datePattern: 'YYYY-MM-DD'
      # 文件大小限制，单位M
      maxSize: '10M'

db:
  mysql:
    host: 'localhost'
    port: 3306
    user: "root"
    password: "wpc123456"
    database: "meeting_room_booking_system"
    pool_size: 10
    synchronize: true
    logging: true

  redis:
    host: '127.0.0.1'
    port: 6379
    database: 1

email:
  host: 'smtp.qq.com'
  port: 587
  secure: false
  user: '755197142@qq.com'
  pass: 'rfznprkjzxeqbeie'


jwt:
  secret: 'secret'
  access_token_expires: '1d'
  refresh_token_expires: '7d'


