application:
  port: 3008
  prefix: "api"


  # 日志配置
  logger:
    level: 'debug'
    dirname: 'logs'
    filename: 'log-%DATE%.log'
    datePattern: 'YYYY-MM-DD'
    # 文件大小限制，单位M
    maxSize: '10M'

db:
  mysql:
    host: mysql-container
    port: 3306
    user: "root"
    password: "wpc123456"
    database: "meeting_room_booking_system"
    pool_size: 10
    synchronize: true
    logging: true

  redis:
    host: redis-container
    port: 6379
    database: 1

email:
  host: 'smtp.qq.com'
  port: 587
  secure: false
  user: '755197142@qq.com'
  pass: 'rfznprkjzxeqbeie'


jwt:
  secret: '4db0cMmgIPOXqEU'
  access_token_expires: '30m'
  refresh_token_expires: '7d'